version: "3.8"
services:
  store:
    container_name: store
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - store_db
    networks:
      - store_network

  store_nginx:
    container_name: store_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - store
    environment:
      NGINX_FPM_HOST: store
      NGINX_ROOT: /usr/src/app/public
    networks:
      - store_network

  store_db:
    container_name: store_db
    image: mysql:8.0.20
    platform: linux/x86_64
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3308:3308
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_TCP_PORT: "3308"
    expose:
      - "3308"
    networks:
      - store_network

networks:
  store_network:
    driver: bridge
